version: "3"

services:

  db:
    image: postgres:13
    container_name: odoo-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    image: odoo:15
    container_name: odoo15
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    command: odoo -c /etc/odoo/odoo.conf